### ISSUE TITLE
Name collision on FreeDOS with DOSSHELL.EXE

### ISSUE THREAD

**Issue by cardpuncher** [ercanersoy/FreeDOS-TUI-Shell#10]
Just as a reminder, when installing FDTUI with FDIMPLES on FreeDOS 1.3-RC5, the user gets an error message telling that dosshell.exe is already present (that's another program); so it may be a good idea to rename FDTUI's dosshell.exe.

**Comment by ercanersoy** [comment]
I solved today.

https://github.com/ercanersoy/FDTUI/commit/7ef5ddd600b6ae8d61d67447022039d3ae90bb35
