### ISSUE TITLE
Problems with some strings in the French translation

### ISSUE THREAD

**Issue by cardpuncher** [ercanersoy/FreeDOS-TUI-Shell#8]
Hello Ercan,

As the attached screenshot shows, there are some problems with the display of some strings in French. For example "Modifier laattribut" should be "Modifier l'attribut". I suspect the ' character is not properly escaped. If you tell me how to correct that, I can happily send a new translation file (I would also like to shorten "Attributs de l'élément" as simply "Attributs", as the whole text doesn't get displayed).

Tested with FreeDOS 1.3-RC5 in VirtualBox on Ubuntu 20.04.3.

![Screenshot at 2021-12-10 12-56-23](https://user-images.githubusercontent.com/64688741/145556173-6ae6fd99-30e9-46c1-a1ca-63e101837fe1.png)

**Comment by ercanersoy** [comment]
Hello,

Thanks. You can send a pull request for French Translation or send me language file.
